services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  dummy:
    image: hello-world
    depends_on:
      postgres:
        condition: service_healthy
