// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	cartservice "route256.ozon.ru/project/cart/internal/service/cart_service"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the ServiceMock type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function with given fields: ctx, userID, skuID, quantity
func (_m *ServiceMock) AddItem(ctx context.Context, userID int64, skuID int64, quantity uint16) error {
	ret := _m.Called(ctx, userID, skuID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, uint16) error); ok {
		r0 = rf(ctx, userID, skuID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type ServiceMock_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - skuID int64
//   - quantity uint16
func (_e *ServiceMock_Expecter) AddItem(ctx interface{}, userID interface{}, skuID interface{}, quantity interface{}) *ServiceMock_AddItem_Call {
	return &ServiceMock_AddItem_Call{Call: _e.mock.On("AddItem", ctx, userID, skuID, quantity)}
}

func (_c *ServiceMock_AddItem_Call) Run(run func(ctx context.Context, userID int64, skuID int64, quantity uint16)) *ServiceMock_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(uint16))
	})
	return _c
}

func (_c *ServiceMock_AddItem_Call) Return(_a0 error) *ServiceMock_AddItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_AddItem_Call) RunAndReturn(run func(context.Context, int64, int64, uint16) error) *ServiceMock_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// Checkout provides a mock function with given fields: ctx, userID
func (_m *ServiceMock) Checkout(ctx context.Context, userID int64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceMock_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type ServiceMock_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ServiceMock_Expecter) Checkout(ctx interface{}, userID interface{}) *ServiceMock_Checkout_Call {
	return &ServiceMock_Checkout_Call{Call: _e.mock.On("Checkout", ctx, userID)}
}

func (_c *ServiceMock_Checkout_Call) Run(run func(ctx context.Context, userID int64)) *ServiceMock_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ServiceMock_Checkout_Call) Return(_a0 int64, _a1 error) *ServiceMock_Checkout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceMock_Checkout_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *ServiceMock_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function with given fields: ctx, userID, skuID
func (_m *ServiceMock) DeleteItem(ctx context.Context, userID int64, skuID int64) error {
	ret := _m.Called(ctx, userID, skuID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, skuID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type ServiceMock_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - skuID int64
func (_e *ServiceMock_Expecter) DeleteItem(ctx interface{}, userID interface{}, skuID interface{}) *ServiceMock_DeleteItem_Call {
	return &ServiceMock_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, userID, skuID)}
}

func (_c *ServiceMock_DeleteItem_Call) Run(run func(ctx context.Context, userID int64, skuID int64)) *ServiceMock_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ServiceMock_DeleteItem_Call) Return(_a0 error) *ServiceMock_DeleteItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_DeleteItem_Call) RunAndReturn(run func(context.Context, int64, int64) error) *ServiceMock_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItemsByUserID provides a mock function with given fields: ctx, userID
func (_m *ServiceMock) DeleteItemsByUserID(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItemsByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_DeleteItemsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItemsByUserID'
type ServiceMock_DeleteItemsByUserID_Call struct {
	*mock.Call
}

// DeleteItemsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ServiceMock_Expecter) DeleteItemsByUserID(ctx interface{}, userID interface{}) *ServiceMock_DeleteItemsByUserID_Call {
	return &ServiceMock_DeleteItemsByUserID_Call{Call: _e.mock.On("DeleteItemsByUserID", ctx, userID)}
}

func (_c *ServiceMock_DeleteItemsByUserID_Call) Run(run func(ctx context.Context, userID int64)) *ServiceMock_DeleteItemsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ServiceMock_DeleteItemsByUserID_Call) Return(_a0 error) *ServiceMock_DeleteItemsByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_DeleteItemsByUserID_Call) RunAndReturn(run func(context.Context, int64) error) *ServiceMock_DeleteItemsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemsByUserID provides a mock function with given fields: ctx, userID
func (_m *ServiceMock) GetItemsByUserID(ctx context.Context, userID int64) (*cartservice.Cart, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetItemsByUserID")
	}

	var r0 *cartservice.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*cartservice.Cart, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *cartservice.Cart); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cartservice.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceMock_GetItemsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemsByUserID'
type ServiceMock_GetItemsByUserID_Call struct {
	*mock.Call
}

// GetItemsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ServiceMock_Expecter) GetItemsByUserID(ctx interface{}, userID interface{}) *ServiceMock_GetItemsByUserID_Call {
	return &ServiceMock_GetItemsByUserID_Call{Call: _e.mock.On("GetItemsByUserID", ctx, userID)}
}

func (_c *ServiceMock_GetItemsByUserID_Call) Run(run func(ctx context.Context, userID int64)) *ServiceMock_GetItemsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ServiceMock_GetItemsByUserID_Call) Return(_a0 *cartservice.Cart, _a1 error) *ServiceMock_GetItemsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceMock_GetItemsByUserID_Call) RunAndReturn(run func(context.Context, int64) (*cartservice.Cart, error)) *ServiceMock_GetItemsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
