// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ClientMock is an autogenerated mock type for the ClientMock type
type ClientMock struct {
	mock.Mock
}

type ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientMock) EXPECT() *ClientMock_Expecter {
	return &ClientMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *ClientMock) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ClientMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ClientMock_Expecter) Close() *ClientMock_Close_Call {
	return &ClientMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ClientMock_Close_Call) Run(run func()) *ClientMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientMock_Close_Call) Return(_a0 error) *ClientMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientMock_Close_Call) RunAndReturn(run func() error) *ClientMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *ClientMock) Get(ctx context.Context, key string) (interface{}, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClientMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *ClientMock_Expecter) Get(ctx interface{}, key interface{}) *ClientMock_Get_Call {
	return &ClientMock_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *ClientMock_Get_Call) Run(run func(ctx context.Context, key string)) *ClientMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientMock_Get_Call) Return(_a0 interface{}, _a1 error) *ClientMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientMock_Get_Call) RunAndReturn(run func(context.Context, string) (interface{}, error)) *ClientMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *ClientMock) Set(ctx context.Context, key string, value interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientMock_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type ClientMock_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - ttl time.Duration
func (_e *ClientMock_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *ClientMock_Set_Call {
	return &ClientMock_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *ClientMock_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, ttl time.Duration)) *ClientMock_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *ClientMock_Set_Call) Return(_a0 error) *ClientMock_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientMock_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *ClientMock_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
