// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stock.proto

package stock

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StockInfoRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StockInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StockInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StockInfoRequestMultiError, or nil if none found.
func (m *StockInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StockInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSku() < 0 {
		err := StockInfoRequestValidationError{
			field:  "Sku",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StockInfoRequestMultiError(errors)
	}

	return nil
}

// StockInfoRequestMultiError is an error wrapping multiple validation errors
// returned by StockInfoRequest.ValidateAll() if the designated constraints
// aren't met.
type StockInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StockInfoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StockInfoRequestMultiError) AllErrors() []error { return m }

// StockInfoRequestValidationError is the validation error returned by
// StockInfoRequest.Validate if the designated constraints aren't met.
type StockInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StockInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StockInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StockInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StockInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StockInfoRequestValidationError) ErrorName() string { return "StockInfoRequestValidationError" }

// Error satisfies the builtin error interface
func (e StockInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStockInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StockInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StockInfoRequestValidationError{}

// Validate checks the field values on StockInfoResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StockInfoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StockInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StockInfoResponseMultiError, or nil if none found.
func (m *StockInfoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StockInfoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	if len(errors) > 0 {
		return StockInfoResponseMultiError(errors)
	}

	return nil
}

// StockInfoResponseMultiError is an error wrapping multiple validation errors
// returned by StockInfoResponse.ValidateAll() if the designated constraints
// aren't met.
type StockInfoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StockInfoResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StockInfoResponseMultiError) AllErrors() []error { return m }

// StockInfoResponseValidationError is the validation error returned by
// StockInfoResponse.Validate if the designated constraints aren't met.
type StockInfoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StockInfoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StockInfoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StockInfoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StockInfoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StockInfoResponseValidationError) ErrorName() string {
	return "StockInfoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StockInfoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStockInfoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StockInfoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StockInfoResponseValidationError{}
